### ISSUE TITLE
Integration Testing of Distributed Metrics

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#105]
Story for Feature #40
Upstream: #788

## Description
As an EDC user, I would like to have guarantees that metrics in the framework is working properly.

## Acceptance Criteria
- [ ] Correct functioning of metric collection in EDC is covered by tests

## Tasks
- [ ] Run integration test to verify that the expected metrics are present using the prometheus endpoint.

**Comment by algattik** [comment]
Suggesting to rather focus right away on an integration test (viz https://github.com/open-telemetry/opentelemetry-java/blob/main/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java) and not include Jaeger in the loop unless absolutely necessary

**Comment by marcgs** [comment]
@algattik Adapted Tasks to reflect that this is indeed the preferred approach and E2E test should be implemented only as a last resort.

**Comment by marcgs** [comment]
Created new story for distributed tracing: https://github.com/agera-edc/DataSpaceConnector/issues/172

**Comment by marcgs** [comment]
> @marcgs general good practice to indicate acceptance criteria tasks as having been met/completed by checking them off

@ouphi as you worked on this one, could you take care of this?
