### ISSUE TITLE
DPF: Azure Data Factory - Async Polling

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#128]
Related to upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/773
Feature #127 

## Description

`DataPlaneManagerImpl` is currently synchronous. This means a thread is hogged for the duration of the transfer, and transfers are lost on crashes. This is not good for potentially large transfers which could last minutes or hours. We could use the state machine library from https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/787 to better support asynchronous poll-based processes.

Jim is also planning to do some refactorings: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/773#issuecomment-1057074265

## Acceptance Criteria

- [ ] Polling for updates is done asynchronously

## Tasks

- [ ] TODO

**Comment by algattik** [comment]
Other limitations to consider:

- A runtime thread is held on to for polling for transfer completion.
- Only Azure blob is supported as both storage and destination.
- Both Azure storage accounts must be accessible from the Internet.
- Only a single named blob can be copied in a data transfer request.
- The transfer must complete in at most 1 hour, or will time out.
- Resources created in Data Factory and Key Vault secrets are not deleted after the run.

**Comment by zeier** [comment]
Moved limitations mentioned above to a dedicated story for refinement.

**Comment by zeier** [comment]
Not planned to cover this item by the Agera crew until end of August.
