### ISSUE TITLE
DataManagementApi - `deleteById` Method for Backing Stores

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#135]
Feature #118 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/801 and https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/802

## Description

Implementation according to upstream issues 801 and 802.

## Acceptance Criteria

- [ ] AssetLoader `Asset deleteById(String assetId)` method is implemented
- [ ] ContractDefinitionLoader `ContractDefinition deleteById(String definitionId)` is implemented
- [ ] Unit tests

**Comment by chrislomonico** [comment]
closing per daily conversation
