### ISSUE TITLE
DataManagementApi - Policy Store

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#136]
Feature #118 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/803

## Description

Implementation of PolicyStore according to upstream issue [803](https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/803).

Note that a Cosmos DB implementation is out of scope, will be in another story.

## Acceptance Criteria

- [ ] PolicyStore in-memory implementation per upstream issue
- [ ] Unit tests

**Comment by chrislomonico** [comment]
@Izzzu have the acceptance criteria been met? If so best practice would be to mark them as such
