### ISSUE TITLE
Spike: Cosmos DB High availability tests

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#183]
Feature #70 
Before #82

# Description

The goal of this Spike is to figure out what would be the best way to achieve Cosmos DB High availability tests from story #82.
We want to make sure that if one consumer replica is not available, the EDC logic is not broken.

A few possibilities are:
- Use the EdcRuntimeExtension to simulate a scenario.
- Use minikube
- Test on a lower level

# Acceptance criteria.
- [ ] The different tested approaches are documented.
- [ ] Decision on what approach will be used in story #82 is taken.
- [ ] Document important scenarios that need to be tested.

**Comment by Izzzu** [comment]
Closing this issue as it's not needed. We found out that the lease mechanism is already tested in in some @AzureCosmosDbIntegrationTest's suites. To achieve #82 missing scenarios can be written in these suites and there's no need to create new test set up for that.
