### ISSUE TITLE
Report for tagged tests

### ISSUE THREAD

**Issue by ouphi** [agera-edc/DataSpaceConnector#203]
Feature #194 
upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1046

# Description

Tagged tests do not appear in the unit test report.
The tests that are tagged with Junit Tag are not running with unit tests, and in CI, the tests are running in a different workflow.

This story is about coming up with a solution to ensure that tagged tests have a report.
The solution could be to have one report grouping all tests or have 2 reports, one for unit tests, one for integration tests.

![Screenshot 2022-03-31 at 12 05 24](https://user-images.githubusercontent.com/17216799/161030854-c586c275-eaa3-419a-9df8-aada43e60cf9.png)

# Acceptance criteria
- [x] The solution is documented
- [x] Tagged tests are visible in a report

**Comment by algattik** [comment]
Blocked by upstream 1034. Spike PR is out that illustrates a solution
