### ISSUE TITLE
DataManagementApi - Transfer Process Controller

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#210]
Feature #118 
Upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1066

## Description

Implementation according to upstream issue 1066.

## Acceptance Criteria

- [ ] Implementation according to the upstream issue is completed
- [ ] Implementation is aligned with the implementation of other controllers
- [ ] Unit tests

**Comment by Izzzu** [comment]
Closing this issue as Andrea took it over to complete the work as it is urgent for the release. 
Internal PR for this: https://github.com/agera-edc/DataSpaceConnector/pull/214 (left in a state where it was picked up by Andrea)

**Comment by Izzzu** [comment]
Closing this issue as Andrea took it over to complete the work as it is urgent for the release. 
Internal PR for this: https://github.com/agera-edc/DataSpaceConnector/pull/214 (left in a state where it was picked up by Andrea)
