### ISSUE TITLE
Transfer process: Consumer does not receive information about failed transfers

### ISSUE THREAD

**Issue by zeier** [agera-edc/DataSpaceConnector#256]
## Description

Fix for upstream bug https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1242

## Acceptance Criteria

- [ ] Upstream bug is closed

**Comment by algattik** [comment]
Pending decision in upstream issue

**Comment by zeier** [comment]
Closing as it will be tracked in upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/1242
