### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#28]
## Description

The goal of this feature is to establish performance tests and use corresponding tools.

## Acceptance Criteria

- [x] Possible tools for performance testing are evaluated
- [x] Tool(s) to be used are agreed on
- [x] Documentation and a first performance test are available
- [x] EDC issues for additional performance tests which would be valuable to be implemented are filed

## Stories

- [x] #81
- [x] #60
- [x] #191

**Comment by zeier** [comment]
Removing benchmarking tools as there are no specific needs at this time.
