### ISSUE TITLE
CodeQL: custom queries and configuration possibilities

### ISSUE THREAD

**Issue by marcgs** [agera-edc/DataSpaceConnector#46]
### Description

Further investigation how CodeQL can be extended and configured for EDC quality metrics

### Acceptance Criteria

- [x] Investigate custom CodeQL queries based on use case provided by Paul
- [x] Investigate possibilities of configuring CodeQL Code Scanning to only show critical findings as well as suppress individual items using a configuration file (instead of using the Github UI). See https://github.blog/changelog/2021-07-19-codeql-code-scanning-new-severity-levels-for-security-alerts/.
- [x] Update ADR to contain the information shared in the spike

See [spike](https://github.com/Agera-CatenaX/EclipseDataSpaceConnector/tree/spike/code-quality-and-test-coverage/docs/codequality) results

**Comment by chrislomonico** [comment]
updated the spike readme to include review of findings
