### ISSUE TITLE
DPF Sample

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#47]
TODO: We talked about creating a sample for the Data Plane framework, which includes usage of the Azure Object Storage Extension (#15). This is a story which will be done later and is not part of feature agera-edc/DataSpaceConnector#20.

**Comment by algattik** [comment]
The story should be about updating sample 04.0 to use DPF, since it's our recommended way of doing file transfers. This can be done after EDC has been updated to use DPF for transfers.
