### ISSUE TITLE
Resilience

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#70]
## Description

The goal of this feature is to improve the resiliency of the EDC by covering the three items below that have been identified as part of our initial EDC feedback.

## Stories

- [x] #86
- [x] #83 
- [x] #183
- [x] #82

**Comment by chrislomonico** [comment]
Assigned for refinement (@cpeeyush @algattik)
As discussed, 3 stories will be removed and combined into a single feature for starting point
