### ISSUE TITLE
Resilience: call TransferProcessListener before state transition

### ISSUE THREAD

**Issue by algattik** [agera-edc/DataSpaceConnector#86]
Feature #70 
Upstream: https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/issues/434

A custom extension may need to perform custom processing after a data transfer has reached a certain stage. For example, in Catena-X PRS, we wanted to run additional transfers recursively after each transfer had completed.

Triggering custom logic on TransferProcess state changes requires registering a TransferProcessListener. However listeners are not guaranteed to be called, e.g. if the instance crashes after persisting the state change but before invoking the listener. Custom logic in the listener can be crucial for the functioning of client applications, thus EDC needs to guarantee that these are called before advancing a transfer process to the next state is made durable.

Based on the discussion with Jim in #434, we want to call the listeners before the state transition is persisted. The semantic will be at-least-once, no ordering guarantees, and only the guarantee that an attempt will eventually be made to persist the processes in the next state

Acceptance criteria

- [ ] `TransferProcessListener` operations are guaranteed to be called at least once even if system fails.

Tasks

- [ ] Call listener operations in `TransferProcessManagerImpl` before persisting state changes.

**Comment by chrislomonico** [comment]
@Izzzu please confirm on the state of the acceptance criteria/tasks (both are unchecked)
