### ISSUE TITLE
Improve Helm chart config mechanism

### ISSUE THREAD

**Issue by arckumari** [agera-edc/DataSpaceConnector#94]
Feature: https://github.com/agera-edc/DataSpaceConnector/issues/33

Description
https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/701

Acceptance Criteria

- [ ]

**Comment by algattik** [comment]
Was just implemented in upstream https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/709, https://github.com/eclipse-dataspaceconnector/DataSpaceConnector/pull/701
